### ISSUE TITLE
`wrangler dev` fails when zone has no apex record

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler-legacy#1788]
#### Describe the bug

If a zone has no apex record, when running `wrangler dev`, the following error shows up:
```
Error: error sending request for url (https://<zone>/cdn-cgi/workers/preview/?s0=<token>): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Either create a new zone, or remove all DNS records from an existing zone
2. Generate a wrangler template, and specify any route to the zone
3. Run `wrangler dev`
4. See the error

#### Expected behavior

Wrangler should instruct the developer to ensure an apex record exists on their zone. 

#### Environment and versions

Fill out the following information about your environment.

* operating system: `macOS Big Sur`
* output of `wrangler -V`: `wrangler 1.11.0`
* output of `node -v`: `v15.4.0`
* content of `wrangler.toml`:
```toml
name = "gamertag"
type = "javascript"
account_id = "..."
zone_id = "..."
workers_dev = false
routes = ["api.gamertag.dev/random"]
```

Note: There is a DNS record for `api.gamertag.dev`, but no record for `gamertag.dev`
