### ISSUE TITLE
workers_dev defined at top-level is not inherited by environments

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler-legacy#1822]
#### Describe the bug

When using the `wrangler.toml` below: 

```toml
name = "my-first-worker"
type = "webpack"
account_id = "..."
workers_dev = true
route = "..."
zone_id = "..."

[env.production]
zone_id = "..."
route = "..."
```

Then running:

```bash
wrangler publish --env production
```

It only deploys to the route, and not workers.dev. Since `workers_dev` is defined at the top-level, the production environment should "inherit" that value. As specified in our docs: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

#### Expected behavior

The above sequence should deploy to both the route and workers.dev.
