### ISSUE TITLE
Environment-specific build `command` requires duplicating `build.upload` rules

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler-legacy#1964]
I have 3 environments, dev/staging/production, pointing to a different `API_HOST`:

```toml
name = "myworker-dev"
type = "javascript"

[vars]
API_HOST = 'https://dev.host'

[build]
command = "yarn build"

[build.upload]
format = "modules"
dir = "dist"
main = "./worker.mjs"

[[build.upload.rules]]
type = "Text"
globs = ["*.pem"]

[env.staging]
name = "myworker-staging"

[env.staging.vars]
API_HOST = 'https://staging.host'

[env.production]
name = "myworker"

[env.production.vars]
API_HOST = 'https://production.host'
```

All works fine as expected. But when i went to customise the `command` section:

```toml
[build]
command = "yarn build:dev"

[env.staging.build]
command = "yarn build:staging"

[env.production.build]
command = "yarn build:staging"
```

I get the following error message:

```
$ wrangler publish -e staging
Error: missing field `upload`
```

It doesn't just break `-e staging` either, the whole `wrangler.toml` file is treated as invalid and _any_ `wrangler` command fails.

To fix, I have to duplicate all the upload values:

```
[env.staging.build.upload]
format = "modules"
dir = "dist"
main = "./worker.mjs"

[[env.staging.build.upload.rules]]
type = "Text"
globs = ["*.pem"]

[env.production.build.upload]
format = "modules"
dir = "dist"
main = "./worker.mjs"

[[env.production.build.upload.rules]]
type = "Text"
globs = ["*.pem"]
```

Any workaround? Is there a way of defining TOML sections as inheriting from others? Can we merge the `[build]` sections and treat them as line-by-line overrides from the base?

**Comment by nilslice** [comment]
Yea, that's not ideal. Can you think of any reason why one _wouldn't_ want those build values inherited between environments? cc/ @Electroid @xortive

**Comment by xortive** [comment]
No, I think they should be inherited

**Comment by hazcod** [comment]
Interestingly I still have the same error with:
```toml
[build]
watch_dir   = "src/"
[env.dev.build]
command     = "npm install && hugo --gc --minify --config=config.dev.yml && npm run build"
[env.dev.build.upload]
format = "service-worker"
[env.prd.build]
command     = "npm install && hugo --gc --minify --config=config.prd.yml && npm run build"
[env.prd.build.upload]
format = "service-worker"
```
