### ISSUE TITLE
`wrangler preview --watch` broken with custom build config

### ISSUE THREAD

**Issue by diced** [cloudflare/wrangler-legacy#2040]
#### Describe the bug
It seems that with a custom build configuration like below, when running `wrangler preview --watch` it just exits instead of watching for any changes when the `watch_dir` is set to the current directory. It works with other directories, yet putting one file in a directory to make that work seems overkill.
```toml
[build]
command = "yarn build"
watch_dir = "."
upload = { format = "service-worker" }
```
`yarn build`: `esbuild index.js --bundle --outfile=dist/index.js`

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Set up a wrangler project
2. Add esbuild to dev dependencies
3. Copy the build script above to `package.json` `scripts.build`
4. Add the custom build config to `wrangler.toml`
5. Run `wrangler preview --watch`

#### Expected behavior

It should just watch for changes instead of exiting with the `--watch` flag, yet seems to behave like it would without it.

#### Environment and versions

Fill out the following information about your environment.

* operating system: `Arch Linux x86_64 (Kernel: 5.13.10-zen1-1-zen)`
* output of `wrangler -V`: `wrangler 1.19.0`
* output of `node -v`: `v16.3.0`
* content of `wrangler.toml`: 
```toml
name = "weather"
type = "javascript"

account_id = "x"
workers_dev = true

routes = [
  "edge.diced.me/weather*",
  "edge.diced.me/weather"
]

zone_id = "x"

[build]
command = "yarn build"
upload = { format = "service-worker" }
```
