### ISSUE TITLE
Support Cloudflare Access with `wrangler dev`

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/wrangler-legacy#2049]
#### Describe the feature

I'm using `wrangler dev` for development, but all URLs protected by Cloudflare Access get redirected to the login page and after a successful login I'm redirected from `http://127.0.0.1:8787` to my production domain.

#### Describe the alternatives

I'm not aware of any alternatives or ways to bypass the login screen and redirect.

**Comment by Electroid** [comment]
Hey @tillkruss, mind providing some more context here about your setup? If I understand correctly: you have a domain that is using Cloudflare Access, you also have a Worker that has a route on that domain, you attempt to run `wrangler dev` on that Worker, and it takes you to the Access login screen? Is that correct?

**Comment by tillkruss** [comment]
Correct the Worker is attached to the domain root and handle website, admin and API requests. 

The `/admin` route is protected with Access and when I request `http://127.0.0.1:8787/admin` I get redirected to the CF Access login page, which I'd like to bypass or get working when using `wrangler dev`.

**Comment by nilslice** [comment]
@tillkruss - would you mind sharing the full `wrangler dev` command you're using, including all the args/params (ensuring nothing private/secret is exposed)

Thanks!

**Comment by tillkruss** [comment]
I just run the plain `wrangler dev`. This is my toml file:

```toml
name = "..."
type = "webpack"
route = "...com/*"
zone_id = ""
account_id = ""
usage_model = "unbound"

kv-namespaces = [
	 { binding = "app", id = "", preview_id = "" },
	 { binding = "metrics", id = "", preview_id = "" },
	 { binding = "leads", id = "", preview_id = "" },
]

[site]
bucket = "./public"

[triggers]
crons = ["*/3 * * * *", "*/10 * * * *"]

[vars]
ENVIRONMENT = "production"
SENTRY_DSN = ""
SENTRY_CLIENT_ID = ""
SENTRY_CLIENT_SECRET = ""
```
