### ISSUE TITLE
`wrangler dev` no longer refreshing the preview token

### ISSUE THREAD

**Issue by hmnd** [cloudflare/wrangler-legacy#2068]
#### Describe the bug

Within 5-15 mins. of starting a `wrangler dev` session, upload builds starts to fail with the following error:
```
⚠️  Something went wrong with the request to Cloudflare...
workers.api.error.expired_preview_token [API code: 10049]
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run `wrangler dev`
2. Run it for a while
3. Trigger a rebuild by changing a file

#### Expected behavior

wrangler should refresh its preview token. #2008 fixed this a couple months ago, but perhaps there was a regression at some point?

#### Environment and versions

Fill out the following information about your environment.

* operating system: Ubuntu 20.04.2 LTS on Windows 10 x86_64
* output of `wrangler -V`: `wrangler 1.19.2`
* output of `node -v`: `v14.17.6
* content of `wrangler.toml`:
```toml
name = "gateway-dev"
type = "javascript"
account_id = "xxx"
webpack_config = "webpack.config.js"
workers_dev = true
vars = { xxx= "xxx", xxx= "xxx" }

[[kv_namespaces]]
binding = "xxx"
preview_id = "xxx"
id = "xxx"

[env.production]
name = "gateway"
workers_dev = true

[[env.production.kv_namespaces]]
binding = "xxx"
preview_id = "xxx"
id = "xxx"

[build]
command = "yarn build"
cwd = "."
watch_dir = "src/"

[build.upload]
format = "service-worker"

[miniflare]
kv_persist = true
```
